//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        public int id { get; set; }
        public string usn { get; set; }
        public Nullable<int> e_id { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Student Student { get; set; }
    }
}
